name: front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  flutter_tesseract_ocr: ^0.4.0 # import for OCR
  image_picker: ^0.8.5+3 # import to take photo
  google_ml_kit: ^0.10.0 # import for ocr
  google_mlkit_barcode_scanning: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/