# Build stage
FROM golang:1.21 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o main .

# Ensure the data directory exists and set permissions
RUN mkdir -p /data && chmod -R 777 /data

# Copy the SQL initialization script
COPY data/init.sql /data/init.sql
COPY data/doc.json /data/doc.json

EXPOSE 8080
CMD ["./main"]

